// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            uuid.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Name          string           `json:"name"`
	Url           string           `json:"url"`
	UserID        uuid.UUID        `json:"user_id"`
	LastFetchedAt pgtype.Timestamp `json:"last_fetched_at"`
}

type FeedFollow struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UserID    uuid.UUID        `json:"user_id"`
	FeedID    uuid.UUID        `json:"feed_id"`
}

type Post struct {
	ID          uuid.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Url         string           `json:"url"`
	FeedID      uuid.UUID        `json:"feed_id"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Name      string           `json:"name"`
	ApiKey    string           `json:"api_key"`
}
